
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class GUI extends javax.swing.JFrame {
    private DatabaseConnector db;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
         db = new DatabaseConnector();
        try{
        db.getConnection();
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }

    
    public void displaySimulatior() {
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        textFieldPassword = new javax.swing.JTextField();
        buttonSignIn = new javax.swing.JButton();
        panelAppMain = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        buttonSignOut = new javax.swing.JButton();
        buttonSettings = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        pEmployeeHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pEmployeeInfo = new javax.swing.JPanel();
        spEmployeeLessons = new javax.swing.JScrollPane();
        tEmployeeLessons = new javax.swing.JTable();
        pManagerHome = new javax.swing.JPanel();
        pManagerContentTable = new javax.swing.JPanel();
        pManagerEmployeeTable = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spManagerEmployeeTable = new javax.swing.JScrollPane();
        tManagerEmployeeTable = new javax.swing.JTable();
        pManagerReportTable = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spManagerReportTable = new javax.swing.JScrollPane();
        tManagerReportTable = new javax.swing.JTable();
        bManagerEmployeeList = new javax.swing.JButton();
        pManagerLogTable = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        spManagerLogTable = new javax.swing.JScrollPane();
        tManagerLogTable = new javax.swing.JTable();
        bManagerEmployeeEdit = new javax.swing.JButton();
        bManagerEmployeReport = new javax.swing.JButton();
        bManagerEmployeeAdd = new javax.swing.JButton();
        bManagerEmployeeLog = new javax.swing.JButton();
        pManagerEmployees = new javax.swing.JPanel();
        pManagerEmployeeEdit = new javax.swing.JPanel();
        pManagerGoals = new javax.swing.JPanel();
        pManagerGoalEdit = new javax.swing.JPanel();
        pManagerLessons = new javax.swing.JPanel();
        pManagerLessonEdit = new javax.swing.JPanel();
        pAuditorHome = new javax.swing.JPanel();
        pSimulator = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Air Traffic Control LCMS");

        panelMain.setPreferredSize(new java.awt.Dimension(800, 600));
        panelMain.setLayout(new java.awt.CardLayout());

        panelLogin.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password:");

        textFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textFieldPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        buttonSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSignIn.setText("Sign In");
        buttonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldUsername))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(buttonSignIn)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        panelMain.add(panelLogin, "panelLogin");

        labelUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsername.setText("[username]");

        buttonSignOut.setText("Sign Out");
        buttonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignOutActionPerformed(evt);
            }
        });

        buttonSettings.setText("Settings");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 556, Short.MAX_VALUE)
                .addComponent(buttonSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSignOut)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(buttonSignOut)
                    .addComponent(buttonSettings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContent.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Current Lessons");

        tEmployeeLessons.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tEmployeeLessons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lesson", "Date", "Completed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spEmployeeLessons.setViewportView(tEmployeeLessons);

        javax.swing.GroupLayout pEmployeeInfoLayout = new javax.swing.GroupLayout(pEmployeeInfo);
        pEmployeeInfo.setLayout(pEmployeeInfoLayout);
        pEmployeeInfoLayout.setHorizontalGroup(
            pEmployeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spEmployeeLessons, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        pEmployeeInfoLayout.setVerticalGroup(
            pEmployeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spEmployeeLessons, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pEmployeeHomeLayout = new javax.swing.GroupLayout(pEmployeeHome);
        pEmployeeHome.setLayout(pEmployeeHomeLayout);
        pEmployeeHomeLayout.setHorizontalGroup(
            pEmployeeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmployeeHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmployeeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEmployeeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pEmployeeHomeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pEmployeeHomeLayout.setVerticalGroup(
            pEmployeeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmployeeHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(pEmployeeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContent.add(pEmployeeHome, "pEmployeeHome");

        pManagerContentTable.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Employee List");

        tManagerEmployeeTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tManagerEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "First Name", "Last Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spManagerEmployeeTable.setViewportView(tManagerEmployeeTable);

        javax.swing.GroupLayout pManagerEmployeeTableLayout = new javax.swing.GroupLayout(pManagerEmployeeTable);
        pManagerEmployeeTable.setLayout(pManagerEmployeeTableLayout);
        pManagerEmployeeTableLayout.setHorizontalGroup(
            pManagerEmployeeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerEmployeeTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerEmployeeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spManagerEmployeeTable, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(pManagerEmployeeTableLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pManagerEmployeeTableLayout.setVerticalGroup(
            pManagerEmployeeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerEmployeeTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spManagerEmployeeTable, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pManagerContentTable.add(pManagerEmployeeTable, "pManagerEmployeeTable");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Employee Report");

        tManagerReportTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tManagerReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lesson", "Score", "Time Started", "Time Completed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spManagerReportTable.setViewportView(tManagerReportTable);

        bManagerEmployeeList.setText("Back");
        bManagerEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeeListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pManagerReportTableLayout = new javax.swing.GroupLayout(pManagerReportTable);
        pManagerReportTable.setLayout(pManagerReportTableLayout);
        pManagerReportTableLayout.setHorizontalGroup(
            pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerReportTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spManagerReportTable, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(pManagerReportTableLayout.createSequentialGroup()
                        .addComponent(bManagerEmployeeList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pManagerReportTableLayout.setVerticalGroup(
            pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerReportTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bManagerEmployeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spManagerReportTable, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        pManagerContentTable.add(pManagerReportTable, "pManagerReportTable");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Employee Log");

        tManagerLogTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tManagerLogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spManagerLogTable.setViewportView(tManagerLogTable);

        javax.swing.GroupLayout pManagerLogTableLayout = new javax.swing.GroupLayout(pManagerLogTable);
        pManagerLogTable.setLayout(pManagerLogTableLayout);
        pManagerLogTableLayout.setHorizontalGroup(
            pManagerLogTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerLogTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerLogTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spManagerLogTable, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(pManagerLogTableLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pManagerLogTableLayout.setVerticalGroup(
            pManagerLogTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerLogTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spManagerLogTable, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pManagerContentTable.add(pManagerLogTable, "pManagerLogTable");

        bManagerEmployeeEdit.setText("Edit");

        bManagerEmployeReport.setText("Report");
        bManagerEmployeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeReportActionPerformed(evt);
            }
        });

        bManagerEmployeeAdd.setText("Add");

        bManagerEmployeeLog.setText("Log");

        javax.swing.GroupLayout pManagerHomeLayout = new javax.swing.GroupLayout(pManagerHome);
        pManagerHome.setLayout(pManagerHomeLayout);
        pManagerHomeLayout.setHorizontalGroup(
            pManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerHomeLayout.createSequentialGroup()
                .addComponent(pManagerContentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bManagerEmployeeEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bManagerEmployeReport, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(bManagerEmployeeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bManagerEmployeeLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pManagerHomeLayout.setVerticalGroup(
            pManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerHomeLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(bManagerEmployeeAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bManagerEmployeeEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bManagerEmployeReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bManagerEmployeeLog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pManagerContentTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelContent.add(pManagerHome, "pManagerHome");

        javax.swing.GroupLayout pManagerEmployeesLayout = new javax.swing.GroupLayout(pManagerEmployees);
        pManagerEmployees.setLayout(pManagerEmployeesLayout);
        pManagerEmployeesLayout.setHorizontalGroup(
            pManagerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerEmployeesLayout.setVerticalGroup(
            pManagerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerEmployees, "pManagerEmployees");

        javax.swing.GroupLayout pManagerEmployeeEditLayout = new javax.swing.GroupLayout(pManagerEmployeeEdit);
        pManagerEmployeeEdit.setLayout(pManagerEmployeeEditLayout);
        pManagerEmployeeEditLayout.setHorizontalGroup(
            pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerEmployeeEditLayout.setVerticalGroup(
            pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerEmployeeEdit, "pManagerEmployeeEdit");

        javax.swing.GroupLayout pManagerGoalsLayout = new javax.swing.GroupLayout(pManagerGoals);
        pManagerGoals.setLayout(pManagerGoalsLayout);
        pManagerGoalsLayout.setHorizontalGroup(
            pManagerGoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerGoalsLayout.setVerticalGroup(
            pManagerGoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerGoals, "pManagerGoals");

        javax.swing.GroupLayout pManagerGoalEditLayout = new javax.swing.GroupLayout(pManagerGoalEdit);
        pManagerGoalEdit.setLayout(pManagerGoalEditLayout);
        pManagerGoalEditLayout.setHorizontalGroup(
            pManagerGoalEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerGoalEditLayout.setVerticalGroup(
            pManagerGoalEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerGoalEdit, "pManagerGoalEdit");

        javax.swing.GroupLayout pManagerLessonsLayout = new javax.swing.GroupLayout(pManagerLessons);
        pManagerLessons.setLayout(pManagerLessonsLayout);
        pManagerLessonsLayout.setHorizontalGroup(
            pManagerLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerLessonsLayout.setVerticalGroup(
            pManagerLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerLessons, "pManagerLessons");

        javax.swing.GroupLayout pManagerLessonEditLayout = new javax.swing.GroupLayout(pManagerLessonEdit);
        pManagerLessonEdit.setLayout(pManagerLessonEditLayout);
        pManagerLessonEditLayout.setHorizontalGroup(
            pManagerLessonEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerLessonEditLayout.setVerticalGroup(
            pManagerLessonEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerLessonEdit, "pManagerLessonEdit");

        javax.swing.GroupLayout pAuditorHomeLayout = new javax.swing.GroupLayout(pAuditorHome);
        pAuditorHome.setLayout(pAuditorHomeLayout);
        pAuditorHomeLayout.setHorizontalGroup(
            pAuditorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pAuditorHomeLayout.setVerticalGroup(
            pAuditorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pAuditorHome, "pAuditorHome");

        javax.swing.GroupLayout pSimulatorLayout = new javax.swing.GroupLayout(pSimulator);
        pSimulator.setLayout(pSimulatorLayout);
        pSimulatorLayout.setHorizontalGroup(
            pSimulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pSimulatorLayout.setVerticalGroup(
            pSimulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pSimulator, "pSimulator");

        javax.swing.GroupLayout panelAppMainLayout = new javax.swing.GroupLayout(panelAppMain);
        panelAppMain.setLayout(panelAppMainLayout);
        panelAppMainLayout.setHorizontalGroup(
            panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAppMainLayout.setVerticalGroup(
            panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAppMainLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 555, Short.MAX_VALUE))
            .addGroup(panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAppMainLayout.createSequentialGroup()
                    .addGap(0, 44, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelMain.add(panelAppMain, "panelAppMain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** Log in button clicked */
    private void buttonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignInActionPerformed
        boolean userfound = true; //set to false when users table is setup with login information
        
        // Check user log in code here
        /*ArrayList<String> users = db.getUserLoginInformation();
        for(int i = 0; i < users.size(); i+=2){
          
            if(textFieldUsername.getText().equals(users.get(i)))
                if(textFieldPassword.getText().equals(users.get(i+1))){
                    userfound = true;
                }
        }        
        */
        
        
        // Send user log in time to database
        
        
        // Switch panelMain card to main app panel
        if(userfound){
            java.awt.CardLayout card = (java.awt.CardLayout) panelMain.getLayout();
            card.show(panelMain, "panelAppMain");

            // Set labelUsername to user's name
            //labelUsername.setText(db.GetEmployeeName(id));

            // Set panelContent card to appropriate content panel
            card = (java.awt.CardLayout) panelContent.getLayout();  
            card.show(panelContent, "pManagerHome");
            // if (user == employee) card.show(panelContent, "pEmployeeHome"); etc...
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid Username/Password");
            textFieldPassword.setText("");
            textFieldUsername.setText("");
            
        }
    }//GEN-LAST:event_buttonSignInActionPerformed

    private void buttonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignOutActionPerformed
        
        // Sign user out, record time, etc...
        
        
        // Switch panelMain card back to login panel
        java.awt.CardLayout card = (java.awt.CardLayout) panelMain.getLayout();
        card.show(panelMain, "panelLogin");        
    }//GEN-LAST:event_buttonSignOutActionPerformed

    private void bManagerEmployeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeReportActionPerformed
       
        // Check selected column, get employee id
        
        
        // Fill tManagerReportTable
        
        
        // Show card pManagerReportTable
        java.awt.CardLayout card = (java.awt.CardLayout) pManagerContentTable.getLayout();
        card.show(pManagerContentTable, "pManagerReportTable"); 

        
    }//GEN-LAST:event_bManagerEmployeReportActionPerformed

    private void bManagerEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeeListActionPerformed
        // Go back to manager's employee table
        java.awt.CardLayout card = (java.awt.CardLayout) pManagerContentTable.getLayout();
        card.show(pManagerContentTable, "pManagerEmployeeTable"); 
    }//GEN-LAST:event_bManagerEmployeeListActionPerformed

    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bManagerEmployeReport;
    private javax.swing.JButton bManagerEmployeeAdd;
    private javax.swing.JButton bManagerEmployeeEdit;
    private javax.swing.JButton bManagerEmployeeList;
    private javax.swing.JButton bManagerEmployeeLog;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JButton buttonSignIn;
    private javax.swing.JButton buttonSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel pAuditorHome;
    private javax.swing.JPanel pEmployeeHome;
    private javax.swing.JPanel pEmployeeInfo;
    private javax.swing.JPanel pManagerContentTable;
    private javax.swing.JPanel pManagerEmployeeEdit;
    private javax.swing.JPanel pManagerEmployeeTable;
    private javax.swing.JPanel pManagerEmployees;
    private javax.swing.JPanel pManagerGoalEdit;
    private javax.swing.JPanel pManagerGoals;
    private javax.swing.JPanel pManagerHome;
    private javax.swing.JPanel pManagerLessonEdit;
    private javax.swing.JPanel pManagerLessons;
    private javax.swing.JPanel pManagerLogTable;
    private javax.swing.JPanel pManagerReportTable;
    private javax.swing.JPanel pSimulator;
    private javax.swing.JPanel panelAppMain;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMain;
    private javax.swing.JScrollPane spEmployeeLessons;
    private javax.swing.JScrollPane spManagerEmployeeTable;
    private javax.swing.JScrollPane spManagerLogTable;
    private javax.swing.JScrollPane spManagerReportTable;
    private javax.swing.JTable tEmployeeLessons;
    private javax.swing.JTable tManagerEmployeeTable;
    private javax.swing.JTable tManagerLogTable;
    private javax.swing.JTable tManagerReportTable;
    private javax.swing.JTextField textFieldPassword;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables
}
