
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class GUI extends javax.swing.JFrame {
    private DatabaseConnector db;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
         db = new DatabaseConnector();
        try{
        db.getConnection();
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }

    
    public void displaySimulatior() {
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        textFieldPassword = new javax.swing.JTextField();
        buttonSignIn = new javax.swing.JButton();
        panelAppMain = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        buttonSignOut = new javax.swing.JButton();
        buttonSettings = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        pEmployeeHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pEmployeeInfo = new javax.swing.JPanel();
        spEmployeeLessons = new javax.swing.JScrollPane();
        tEmployeeLessons = new javax.swing.JTable();
        pManagerHome = new javax.swing.JPanel();
        pManagerContentTable = new javax.swing.JPanel();
        pManagerEmployeeTable = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spManagerEmployeeTable = new javax.swing.JScrollPane();
        tManagerEmployeeTable = new javax.swing.JTable();
        pManagerReportTable = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spManagerReportTable = new javax.swing.JScrollPane();
        tManagerReportTable = new javax.swing.JTable();
        bManagerEmployeeList1 = new javax.swing.JButton();
        pManagerLogTable = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        spManagerLogTable = new javax.swing.JScrollPane();
        tManagerLogTable = new javax.swing.JTable();
        bManagerEmployeeList2 = new javax.swing.JButton();
        pManagerSidePanel = new javax.swing.JPanel();
        bManagerEmployeeAdd = new javax.swing.JButton();
        bManagerEmployeeEdit = new javax.swing.JButton();
        bManagerEmployeReport = new javax.swing.JButton();
        bManagerEmployeeLog = new javax.swing.JButton();
        pManagerEmployeeEdit = new javax.swing.JPanel();
        labelEmployeeEdit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_fName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_lName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bEmployeeEditCancel = new javax.swing.JButton();
        bEmployeeEditSave = new javax.swing.JButton();
        bEmployeeEditDelete = new javax.swing.JButton();
        pManagerGoals = new javax.swing.JPanel();
        pManagerGoalEdit = new javax.swing.JPanel();
        pManagerLessons = new javax.swing.JPanel();
        pManagerLessonEdit = new javax.swing.JPanel();
        pAuditorHome = new javax.swing.JPanel();
        pSimulator = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Air Traffic Control LCMS");

        panelMain.setPreferredSize(new java.awt.Dimension(800, 600));
        panelMain.setLayout(new java.awt.CardLayout());

        panelLogin.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password:");

        textFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textFieldPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        buttonSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSignIn.setText("Sign In");
        buttonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldUsername))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(buttonSignIn)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        panelMain.add(panelLogin, "panelLogin");

        labelUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsername.setText("[username]");

        buttonSignOut.setText("Sign Out");
        buttonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignOutActionPerformed(evt);
            }
        });

        buttonSettings.setText("Settings");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 556, Short.MAX_VALUE)
                .addComponent(buttonSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSignOut)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(buttonSignOut)
                    .addComponent(buttonSettings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContent.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Current Lessons");

        tEmployeeLessons.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tEmployeeLessons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lesson", "Date", "Completed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spEmployeeLessons.setViewportView(tEmployeeLessons);

        javax.swing.GroupLayout pEmployeeInfoLayout = new javax.swing.GroupLayout(pEmployeeInfo);
        pEmployeeInfo.setLayout(pEmployeeInfoLayout);
        pEmployeeInfoLayout.setHorizontalGroup(
            pEmployeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spEmployeeLessons, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        pEmployeeInfoLayout.setVerticalGroup(
            pEmployeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spEmployeeLessons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pEmployeeHomeLayout = new javax.swing.GroupLayout(pEmployeeHome);
        pEmployeeHome.setLayout(pEmployeeHomeLayout);
        pEmployeeHomeLayout.setHorizontalGroup(
            pEmployeeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmployeeHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmployeeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEmployeeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pEmployeeHomeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pEmployeeHomeLayout.setVerticalGroup(
            pEmployeeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmployeeHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pEmployeeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContent.add(pEmployeeHome, "pEmployeeHome");

        pManagerContentTable.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Employee List");

        tManagerEmployeeTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tManagerEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "First Name", "Last Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spManagerEmployeeTable.setViewportView(tManagerEmployeeTable);

        javax.swing.GroupLayout pManagerEmployeeTableLayout = new javax.swing.GroupLayout(pManagerEmployeeTable);
        pManagerEmployeeTable.setLayout(pManagerEmployeeTableLayout);
        pManagerEmployeeTableLayout.setHorizontalGroup(
            pManagerEmployeeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerEmployeeTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerEmployeeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spManagerEmployeeTable, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(pManagerEmployeeTableLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pManagerEmployeeTableLayout.setVerticalGroup(
            pManagerEmployeeTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerEmployeeTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spManagerEmployeeTable, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pManagerContentTable.add(pManagerEmployeeTable, "pManagerEmployeeTable");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("[employee name]'s Report");

        tManagerReportTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tManagerReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lesson", "Score", "Time Started", "Time Completed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spManagerReportTable.setViewportView(tManagerReportTable);

        bManagerEmployeeList1.setText("Back");
        bManagerEmployeeList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeeList1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pManagerReportTableLayout = new javax.swing.GroupLayout(pManagerReportTable);
        pManagerReportTable.setLayout(pManagerReportTableLayout);
        pManagerReportTableLayout.setHorizontalGroup(
            pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerReportTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spManagerReportTable, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(pManagerReportTableLayout.createSequentialGroup()
                        .addComponent(bManagerEmployeeList1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pManagerReportTableLayout.setVerticalGroup(
            pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerReportTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerReportTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pManagerReportTableLayout.createSequentialGroup()
                        .addComponent(bManagerEmployeeList1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spManagerReportTable, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pManagerContentTable.add(pManagerReportTable, "pManagerReportTable");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("[employee name]'s Log");
        jLabel6.setToolTipText("");

        tManagerLogTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tManagerLogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spManagerLogTable.setViewportView(tManagerLogTable);

        bManagerEmployeeList2.setText("Back");
        bManagerEmployeeList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeeList2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pManagerLogTableLayout = new javax.swing.GroupLayout(pManagerLogTable);
        pManagerLogTable.setLayout(pManagerLogTableLayout);
        pManagerLogTableLayout.setHorizontalGroup(
            pManagerLogTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerLogTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerLogTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spManagerLogTable, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(pManagerLogTableLayout.createSequentialGroup()
                        .addComponent(bManagerEmployeeList2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pManagerLogTableLayout.setVerticalGroup(
            pManagerLogTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerLogTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerLogTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pManagerLogTableLayout.createSequentialGroup()
                        .addComponent(bManagerEmployeeList2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spManagerLogTable, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pManagerContentTable.add(pManagerLogTable, "pManagerLogTable");

        pManagerSidePanel.setBackground(new java.awt.Color(230, 230, 230));

        bManagerEmployeeAdd.setText("Add Employee");
        bManagerEmployeeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeeAddActionPerformed(evt);
            }
        });

        bManagerEmployeeEdit.setText("Edit Employee");
        bManagerEmployeeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeeEditActionPerformed(evt);
            }
        });

        bManagerEmployeReport.setText("View Report");
        bManagerEmployeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeReportActionPerformed(evt);
            }
        });

        bManagerEmployeeLog.setText("View Log");
        bManagerEmployeeLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManagerEmployeeLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pManagerSidePanelLayout = new javax.swing.GroupLayout(pManagerSidePanel);
        pManagerSidePanel.setLayout(pManagerSidePanelLayout);
        pManagerSidePanelLayout.setHorizontalGroup(
            pManagerSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pManagerSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bManagerEmployeeLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bManagerEmployeeAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(bManagerEmployeeEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bManagerEmployeReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pManagerSidePanelLayout.setVerticalGroup(
            pManagerSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bManagerEmployeeAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bManagerEmployeeEdit)
                .addGap(33, 33, 33)
                .addComponent(bManagerEmployeReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bManagerEmployeeLog)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pManagerHomeLayout = new javax.swing.GroupLayout(pManagerHome);
        pManagerHome.setLayout(pManagerHomeLayout);
        pManagerHomeLayout.setHorizontalGroup(
            pManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerHomeLayout.createSequentialGroup()
                .addComponent(pManagerContentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pManagerSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pManagerHomeLayout.setVerticalGroup(
            pManagerHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pManagerContentTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pManagerHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pManagerSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContent.add(pManagerHome, "pManagerHome");

        labelEmployeeEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmployeeEdit.setText("Add/Edit Employee");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("ID");

        tf_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("First Name");

        tf_fName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Last Name");

        tf_lName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Address");

        tf_address.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("etc...");

        bEmployeeEditCancel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bEmployeeEditCancel.setText("Cancel");
        bEmployeeEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmployeeEditCancelActionPerformed(evt);
            }
        });

        bEmployeeEditSave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bEmployeeEditSave.setText("Add/Save");
        bEmployeeEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmployeeEditSaveActionPerformed(evt);
            }
        });

        bEmployeeEditDelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bEmployeeEditDelete.setText("Delete");
        bEmployeeEditDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmployeeEditDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pManagerEmployeeEditLayout = new javax.swing.GroupLayout(pManagerEmployeeEdit);
        pManagerEmployeeEdit.setLayout(pManagerEmployeeEditLayout);
        pManagerEmployeeEditLayout.setHorizontalGroup(
            pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerEmployeeEditLayout.createSequentialGroup()
                .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pManagerEmployeeEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelEmployeeEdit))
                    .addGroup(pManagerEmployeeEditLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pManagerEmployeeEditLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_address, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pManagerEmployeeEditLayout.createSequentialGroup()
                                    .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel8))
                                    .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pManagerEmployeeEditLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(tf_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pManagerEmployeeEditLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tf_fName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tf_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(pManagerEmployeeEditLayout.createSequentialGroup()
                                .addComponent(bEmployeeEditSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEmployeeEditCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEmployeeEditDelete)))))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        pManagerEmployeeEditLayout.setVerticalGroup(
            pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pManagerEmployeeEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEmployeeEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addGroup(pManagerEmployeeEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEmployeeEditSave)
                    .addComponent(bEmployeeEditCancel)
                    .addComponent(bEmployeeEditDelete))
                .addGap(44, 44, 44))
        );

        panelContent.add(pManagerEmployeeEdit, "pManagerEmployeeEdit");

        javax.swing.GroupLayout pManagerGoalsLayout = new javax.swing.GroupLayout(pManagerGoals);
        pManagerGoals.setLayout(pManagerGoalsLayout);
        pManagerGoalsLayout.setHorizontalGroup(
            pManagerGoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerGoalsLayout.setVerticalGroup(
            pManagerGoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerGoals, "pManagerGoals");

        javax.swing.GroupLayout pManagerGoalEditLayout = new javax.swing.GroupLayout(pManagerGoalEdit);
        pManagerGoalEdit.setLayout(pManagerGoalEditLayout);
        pManagerGoalEditLayout.setHorizontalGroup(
            pManagerGoalEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerGoalEditLayout.setVerticalGroup(
            pManagerGoalEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerGoalEdit, "pManagerGoalEdit");

        javax.swing.GroupLayout pManagerLessonsLayout = new javax.swing.GroupLayout(pManagerLessons);
        pManagerLessons.setLayout(pManagerLessonsLayout);
        pManagerLessonsLayout.setHorizontalGroup(
            pManagerLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerLessonsLayout.setVerticalGroup(
            pManagerLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerLessons, "pManagerLessons");

        javax.swing.GroupLayout pManagerLessonEditLayout = new javax.swing.GroupLayout(pManagerLessonEdit);
        pManagerLessonEdit.setLayout(pManagerLessonEditLayout);
        pManagerLessonEditLayout.setHorizontalGroup(
            pManagerLessonEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pManagerLessonEditLayout.setVerticalGroup(
            pManagerLessonEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pManagerLessonEdit, "pManagerLessonEdit");

        javax.swing.GroupLayout pAuditorHomeLayout = new javax.swing.GroupLayout(pAuditorHome);
        pAuditorHome.setLayout(pAuditorHomeLayout);
        pAuditorHomeLayout.setHorizontalGroup(
            pAuditorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pAuditorHomeLayout.setVerticalGroup(
            pAuditorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pAuditorHome, "pAuditorHome");

        javax.swing.GroupLayout pSimulatorLayout = new javax.swing.GroupLayout(pSimulator);
        pSimulator.setLayout(pSimulatorLayout);
        pSimulatorLayout.setHorizontalGroup(
            pSimulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pSimulatorLayout.setVerticalGroup(
            pSimulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        panelContent.add(pSimulator, "pSimulator");

        javax.swing.GroupLayout panelAppMainLayout = new javax.swing.GroupLayout(panelAppMain);
        panelAppMain.setLayout(panelAppMainLayout);
        panelAppMainLayout.setHorizontalGroup(
            panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAppMainLayout.setVerticalGroup(
            panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAppMainLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 555, Short.MAX_VALUE))
            .addGroup(panelAppMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAppMainLayout.createSequentialGroup()
                    .addGap(0, 44, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelMain.add(panelAppMain, "panelAppMain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** Log in button clicked */
    private void buttonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignInActionPerformed
        boolean userfound = true; //set to false when users table is setup with login information
        
        // Check user log in code here
        /*ArrayList<String> users = db.getUserLoginInformation();
        for(int i = 0; i < users.size(); i+=2){
          
            if(textFieldUsername.getText().equals(users.get(i)))
                if(textFieldPassword.getText().equals(users.get(i+1))){
                    userfound = true;
                }
        }        
        */
        
        
        // Send user log in time to database
        //db.updateLog(id, "Signed In", time);
        
        
        // Switch panelMain card to main app panel
        if(userfound){
            java.awt.CardLayout card = (java.awt.CardLayout) panelMain.getLayout();
            card.show(panelMain, "panelAppMain");

            // Set labelUsername to user's name
            //labelUsername.setText(db.GetEmployeeName(id));

            // Set panelContent card to appropriate content panel
            card = (java.awt.CardLayout) panelContent.getLayout();  
            card.show(panelContent, "pManagerHome");
            // if (user == employee) card.show(panelContent, "pEmployeeHome"); etc...
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid Username/Password");
            textFieldPassword.setText("");
            textFieldUsername.setText("");
            
        }
    }//GEN-LAST:event_buttonSignInActionPerformed

    private void buttonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignOutActionPerformed
        
        // Sign user out, record time, etc...
        //db.updateLog(id, "Signed Out", time);
        
        
        // Switch panelMain card back to login panel
        java.awt.CardLayout card = (java.awt.CardLayout) panelMain.getLayout();
        card.show(panelMain, "panelLogin");        
    }//GEN-LAST:event_buttonSignOutActionPerformed

    private void bManagerEmployeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeReportActionPerformed
       
        // Check selected column, get employee id (unless already on Log page)
        
        
        // Fill tManagerReportTable
        
        
        // Show card pManagerReportTable
        java.awt.CardLayout card = (java.awt.CardLayout) pManagerContentTable.getLayout();
        card.show(pManagerContentTable, "pManagerReportTable");        
    }//GEN-LAST:event_bManagerEmployeReportActionPerformed

    private void bManagerEmployeeList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeeList1ActionPerformed
        // Go back to manager's employee table
        java.awt.CardLayout card = (java.awt.CardLayout) pManagerContentTable.getLayout();
        card.show(pManagerContentTable, "pManagerEmployeeTable"); 
    }//GEN-LAST:event_bManagerEmployeeList1ActionPerformed

    private void bManagerEmployeeList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeeList2ActionPerformed
        // Go back to manager's employee table
        java.awt.CardLayout card = (java.awt.CardLayout) pManagerContentTable.getLayout();
        card.show(pManagerContentTable, "pManagerEmployeeTable");         
    }//GEN-LAST:event_bManagerEmployeeList2ActionPerformed

    private void bManagerEmployeeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeeAddActionPerformed
        // Change labels for 'Add Employee'
        labelEmployeeEdit.setText("Add Employee");
        bEmployeeEditSave.setText("Add");
        
        // Hide 'Delete Employee' button
        bEmployeeEditDelete.setVisible(false);
        
        // Set card to employee add/edit panel
        java.awt.CardLayout card = (java.awt.CardLayout) panelContent.getLayout();
        card.show(panelContent, "pManagerEmployeeEdit");
    }//GEN-LAST:event_bManagerEmployeeAddActionPerformed

    private void bManagerEmployeeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeeEditActionPerformed
        // Change labels for 'Edit Employee'
        labelEmployeeEdit.setText("Edit Employee");
        bEmployeeEditSave.setText("Save");
        
        // Show 'Delete Employee' button
        bEmployeeEditDelete.setVisible(true);
        
        // Fill in text field with appropriate information
        

        // Set card to employee add/edit panel
        java.awt.CardLayout card = (java.awt.CardLayout) panelContent.getLayout();
        card.show(panelContent, "pManagerEmployeeEdit");
    }//GEN-LAST:event_bManagerEmployeeEditActionPerformed

    private void bManagerEmployeeLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManagerEmployeeLogActionPerformed
               
        // Check selected column, get employee id (unless already on Report page)
        
        
        // Fill tManagerLogTable
        
        
        // Show card pManagerLogTable
        java.awt.CardLayout card = (java.awt.CardLayout) pManagerContentTable.getLayout();
        card.show(pManagerContentTable, "pManagerLogTable");        
    }//GEN-LAST:event_bManagerEmployeeLogActionPerformed

    private void bEmployeeEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmployeeEditSaveActionPerformed
        // Get form info
        try {
            int id = Integer.parseInt(tf_id.getText());
            String fName    = tf_fName.getText();
            String lName    = tf_lName.getText();
            String address  = tf_address.getText();
            
            // Save existing employee
            if (labelEmployeeEdit.getText().equals("Edit Employee")) {
                //db.updateEmployeeInfo(id, fName, lName, address);   
                
                // Verification message
                JOptionPane.showMessageDialog(this, "Employee info saved.");
            }
            // Add new employee
            else {
                //db.addNewEmployee(id, fName, lName, address);  
                
                // Verification message
                JOptionPane.showMessageDialog(this, "Employee added.");
            }   
            
            // Go back to manager home panel
            java.awt.CardLayout card = (java.awt.CardLayout) panelContent.getLayout();  
            card.show(panelContent, "pManagerHome");
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ID, must be an integer.");
        }       
    }//GEN-LAST:event_bEmployeeEditSaveActionPerformed

    private void bEmployeeEditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmployeeEditCancelActionPerformed
        // Go back to manager home panel
        java.awt.CardLayout card = (java.awt.CardLayout) panelContent.getLayout();  
        card.show(panelContent, "pManagerHome");
    }//GEN-LAST:event_bEmployeeEditCancelActionPerformed

    private void bEmployeeEditDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmployeeEditDeleteActionPerformed
        // Delete employee from database
        
        
        
    }//GEN-LAST:event_bEmployeeEditDeleteActionPerformed

    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEmployeeEditCancel;
    private javax.swing.JButton bEmployeeEditDelete;
    private javax.swing.JButton bEmployeeEditSave;
    private javax.swing.JButton bManagerEmployeReport;
    private javax.swing.JButton bManagerEmployeeAdd;
    private javax.swing.JButton bManagerEmployeeEdit;
    private javax.swing.JButton bManagerEmployeeList1;
    private javax.swing.JButton bManagerEmployeeList2;
    private javax.swing.JButton bManagerEmployeeLog;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JButton buttonSignIn;
    private javax.swing.JButton buttonSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelEmployeeEdit;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel pAuditorHome;
    private javax.swing.JPanel pEmployeeHome;
    private javax.swing.JPanel pEmployeeInfo;
    private javax.swing.JPanel pManagerContentTable;
    private javax.swing.JPanel pManagerEmployeeEdit;
    private javax.swing.JPanel pManagerEmployeeTable;
    private javax.swing.JPanel pManagerGoalEdit;
    private javax.swing.JPanel pManagerGoals;
    private javax.swing.JPanel pManagerHome;
    private javax.swing.JPanel pManagerLessonEdit;
    private javax.swing.JPanel pManagerLessons;
    private javax.swing.JPanel pManagerLogTable;
    private javax.swing.JPanel pManagerReportTable;
    private javax.swing.JPanel pManagerSidePanel;
    private javax.swing.JPanel pSimulator;
    private javax.swing.JPanel panelAppMain;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMain;
    private javax.swing.JScrollPane spEmployeeLessons;
    private javax.swing.JScrollPane spManagerEmployeeTable;
    private javax.swing.JScrollPane spManagerLogTable;
    private javax.swing.JScrollPane spManagerReportTable;
    private javax.swing.JTable tEmployeeLessons;
    private javax.swing.JTable tManagerEmployeeTable;
    private javax.swing.JTable tManagerLogTable;
    private javax.swing.JTable tManagerReportTable;
    private javax.swing.JTextField textFieldPassword;
    private javax.swing.JTextField textFieldUsername;
    private javax.swing.JTextField tf_address;
    private javax.swing.JTextField tf_fName;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_lName;
    // End of variables declaration//GEN-END:variables
}
